2024-11-17 01:24:35,100 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Yed\PycharmProjects\pythonProject\module_12\tests_12_4.py", line 30, in test_run
    tr1 = rtwe.Runner(7, 10)
          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yed\PycharmProjects\pythonProject\module_12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-11-17 01:24:35,103 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\Yed\PycharmProjects\pythonProject\module_12\tests_12_4.py", line 17, in test_walk
    tw1 = rtwe.Runner('runner_walk', -10)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yed\PycharmProjects\pythonProject\module_12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -10
